[package]
name = "rest-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
reqwest = "0.11.23"
scraper = "0.18.1"
tokio = { version = "1.35.1", features = ["full"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

